# Generated by Django 5.2.13 on 2026-07-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_pendingregistration_alter_carousel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
